
# first we print the list of students
puts "The students of my cohort at Makers Academy"
puts "--------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts"Nurse Ratched"
puts "Michael Corleone"
puts "Alex De Large"
puts "The Alien"
puts "Terminator"
puts "Freddy Kruger"
puts "The Joker"
puts "Erik Griffin"
puts "Julian Veling"
puts "Alex Parkinson"
puts "Louise Beh"
puts "Sean Haughton"
puts "Edward Brown"
puts "Kate Beavis"
puts "Thomas Strothjohann"
puts "Kevin Lanzon"
puts "Yannick B."
puts "Meads Chalcroft"
puts "Gabriel Arafa"
puts "Sebastien Pires"
puts "Jordan Poultron"
puts "Tom Coakes"
puts "Vanessa Virgitti"
puts "Paul Fitzgerald"
puts "Carrie Christenson"
puts "Diego Romero"
# finally we print the total
print "Overall, we have "
# It's important that print() doesn't add new line characters
print 28
puts " great students"